### ISSUE TITLE
Problems with sass @extend and cascading order

### ISSUE THREAD

**Issue by niceoutput** [JohnCashmore/grunt-combine-media-queries#6]
When i was extending a class `@extend .class-name` and if that extended class was affected by a media-querie it will affect the cascading order. Example:

```css
.class-name {
        @extend .extended-class-name;
        padding: 100px 0;
    }

@media (max-width: 768px) {
      .extended-class-name {
           padding: 0;
     }
}


```
The extended class will override the default `.class-name` attribute. There's a way to put the media queries on top of the css file?
